/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_2;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.*;
import static library_2.LIBRARY_2.audio;

/**
 *
 * @author akash
 */
public class ACCOUNT_OFFICE_M extends javax.swing.JFrame {
    private ImageIcon format =null;
String filename=null;
byte i=0;
byte z=0;
byte k=0;
byte m =0;
byte n=0;
byte[] pic1=null;
    public ImageIcon resizeimage(String imagepath)
{
  ImageIcon MyImage= new ImageIcon(imagepath);
  Image img = MyImage.getImage();
  Image newImg = img.getScaledInstance(lb1.getWidth(), lb1.getHeight(),Image.SCALE_SMOOTH);
  ImageIcon image = new ImageIcon(newImg);
  return image;
}

    /**
     * Creates new form MANAGEMENT
     */
    public ACCOUNT_OFFICE_M() {
        initComponents();
        setIcon();
         bg1.add(rb1);
bg1.add(rb2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(645, 260));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/manage.png"))); // NOI18N
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 76, 90, 20);

        jLabel2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/turtle.png"))); // NOI18N
        jLabel2.setText("REGISTRATION NUMBER");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 106, 210, 20);

        lb3.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        lb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/greenfile.png"))); // NOI18N
        lb3.setText("PASSWORD");
        getContentPane().add(lb3);
        lb3.setBounds(10, 146, 120, 20);

        tf1.setBackground(new java.awt.Color(204, 204, 255));
        tf1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(tf1);
        tf1.setBounds(220, 70, 182, 21);

        tf2.setBackground(new java.awt.Color(204, 204, 255));
        tf2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        tf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf2KeyReleased(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(220, 110, 182, 21);

        tf3.setBackground(new java.awt.Color(204, 204, 255));
        tf3.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        tf3.setToolTipText("CHOOSE ANY COMBINATION OF 4 DIGIT NUMBER ( NO ALPHABETS ).");
        tf3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf3FocusGained(evt);
            }
        });
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf3KeyReleased(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(220, 150, 182, 21);

        tf4.setBackground(new java.awt.Color(204, 204, 255));
        tf4.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(tf4);
        tf4.setBounds(220, 190, 182, 21);

        b1.setBackground(new java.awt.Color(102, 102, 102));
        b1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/attach.png"))); // NOI18N
        b1.setText("ATTACH FILE");
        b1.setBorder(null);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(10, 189, 160, 20);

        b3.setBackground(new java.awt.Color(102, 102, 102));
        b3.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/cross.png"))); // NOI18N
        b3.setText("REMOVE MEMBER");
        b3.setBorder(null);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(430, 139, 190, 20);

        lb1.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(lb1);
        lb1.setBounds(470, 10, 130, 110);

        b2.setBackground(new java.awt.Color(102, 102, 102));
        b2.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/save.png"))); // NOI18N
        b2.setText("ADD MEMBER");
        b2.setBorder(null);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(430, 169, 190, 20);

        jLabel5.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/manage.png"))); // NOI18N
        jLabel5.setText("ACCOUNT OFFICE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 10, 181, 18);

        rb1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        rb1.setText("ADD");
        rb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb1MouseClicked(evt);
            }
        });
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(10, 40, 70, 23);

        rb2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        rb2.setText("REMOVE");
        rb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb2MouseClicked(evt);
            }
        });
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(290, 40, 100, 23);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/refresh.png"))); // NOI18N
        jButton1.setText("REFRESH");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 199, 190, 20);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/clear.png"))); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 229, 160, 20);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/color.png"))); // NOI18N
        jButton3.setText("BACK");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 229, 180, 20);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/exit.png"))); // NOI18N
        jButton4.setText("LOGOUT");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(430, 229, 190, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/Untitled4.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 720, 260);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
b2.setVisible(false);
b3.setVisible(false);
        audio(17);
tf2.setText("AO");
jButton2.setIconTextGap(50);
jButton3.setIconTextGap(75);
jButton4.setIconTextGap(70);
jButton1.setIconTextGap(70);
b2.setIconTextGap(30);
    }//GEN-LAST:event_formWindowOpened

    private void tf2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyReleased
try
{
        if(i==1)
{

try{
    if(tf2.getText().length()==15)
{
     ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from ao_reg_no");
                    while(rs.next())
                    {
                        if(tf2.getText().equals(rs.getString("reg_no")))
                        {
                           
                            tf1.setText(rs.getString("name"));
                             byte [] imagedata = rs.getBytes("pic");
    format = new ImageIcon(imagedata);
    lb1.setIcon(format);

                        }
                    }
   
}
    else if(tf2.getText().length()>15)
            {
 audio(19);
             JOptionPane.showMessageDialog(null,"PLEASE ENTER THE VALID REGESTRATION NUMBER");
             tf1.setText("");
             tf2.setText("AO");
             lb1.setIcon(null);
            }

                   
                }
                catch(Exception e)
                {
                }    
}
else
{
        if(tf2.getText().length()==15)
{
    try
{
    String s5=tf2.getText();
ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from ao_reg_no");
 while(rs.next())
       {
         String  s4=rs.getString("reg_no");
         if(s4.equals(s5))
           {
          z=1;
audio(19);
           JOptionPane.showMessageDialog(null,"PLEASE ENTER THE VALID REGESTRATION NUMBER");
             tf2.setText("AO");
           }
       }
}
catch(Exception e)
{
    
}
    tf3.requestFocus();
}
        if(z==0)
        {
if(tf2.getText().length()>15)
{
audio(19);
    JOptionPane.showMessageDialog(null,"PLEASE ENTER A VALID REGESTRATION NUMBER");
    tf2.setText("AO");
}
}
}
}
    
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_tf2KeyReleased

    private void tf3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyReleased
try
{
        if(tf3.getText().length()==4)
{
    tf4.requestFocus();
}
if (tf3.getText().length()>4)
{
audio(28);
JOptionPane.showMessageDialog(null,"PLEASE ENTER A 4 DIGIT PASSWORD");
    tf3.setText("");    
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}

    }//GEN-LAST:event_tf3KeyReleased

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
try
{
    audio(32);
        JFileChooser c = new JFileChooser();
c.setCurrentDirectory(new File(System.getProperty("user.home")));
FileNameExtensionFilter filter = new FileNameExtensionFilter("*Images","png");
c.addChoosableFileFilter(filter);
int result = c.showSaveDialog(null);
if(result == JFileChooser.APPROVE_OPTION)
{
    File f = c.getSelectedFile();
     filename=f.getAbsolutePath();
    lb1.setIcon(resizeimage(filename));
    tf4.setText(filename);
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
try
{
    audio(32);
        try
{
        if((tf1.getText().length()==0) || (tf2.getText().length()==2) || (tf3.getText().length()==0) || (tf4.getText().length()==0))
{
    k=1;
audio(29);
     JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE DETAILS");

}
}
catch(Exception e)
{
    
}
if(k==0)
{
        i=0;
        String s1=tf1.getText();
String s2=tf2.getText();
int s3 =Integer.parseInt(tf3.getText());

        try
{
File image = new File(filename);
FileInputStream fis = new FileInputStream(image);
ByteArrayOutputStream bos = new ByteArrayOutputStream();
byte []buf = new byte[1024];
for(int readNum;(readNum=fis.read(buf))!=-1;)
{
    bos.write(buf,0,readNum);
}
pic1 = bos.toByteArray();
}
catch(Exception e)
{
    
}
        
try
{

PreparedStatement pst=LIBRARY_2.conn.prepareStatement("insert into ao_reg_no(name,reg_no,password,pic) values (?,?,?,?)");
pst.setString(1, s1);
pst.setString(2, s2);
pst.setInt(3, s3);
pst.setBytes(4,pic1);
pst.execute();
audio(18); 
JOptionPane.showMessageDialog(null,"DATA SAVED SUCCESSFULLY");
tf1.setText("");
tf2.setText("AO");
tf3.setText("");
tf4.setText("");
lb1.setIcon(null);
}
catch (Exception e)
{
 JOptionPane.showMessageDialog(null, e.getMessage());
 System.out.println(e.getMessage());
 e.printStackTrace();
}   
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"PASSWORD SHOULD BE A COMBINATION OF 4 DIGIT NUMBER. ALPHABETS ARE NOT ALLOWED");
}
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
audio(32);
        try
        {
            try{
    
        if((tf1.getText().length()==0) || (tf2.getText().length()==2))
{
    m=1;
audio(29); 
    JOptionPane.showMessageDialog(null, "PLEASE FILL ALL THE DETAILS");

}
}
catch(Exception e)
{
}
if(m==0)
{
    try
    {
      String s5=tf2.getText();
ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from ao_reg_no");
 while(rs.next())
       {
         String  s4=rs.getString("reg_no");
         if(s4.equals(s5))
           {
          n=1;
          
           }
       }   
    }
    catch(Exception e)
    {
        
    }
    if(n==1)
    {
        i=0;
try
{      
String sql = "delete from ao_reg_no where reg_no='"+tf2.getText()+"'";
PreparedStatement pst = null;
pst = LIBRARY_2.conn.prepareStatement(sql);
pst.execute();
audio(30); 
JOptionPane.showMessageDialog(null, "DATA DELETED SUCCESSFULLY");
tf1.setText("");
tf2.setText("AO");
lb1.setIcon(null);
i=1;
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,e.getMessage());
}
}
    else
            {
                audio(19);
             JOptionPane.showMessageDialog(null,"PLEASE ENTER THE VALID REGESTRATION NUMBER");
             tf1.setText("");
             tf2.setText("AO");
             lb1.setIcon(null);
            }
}
        }
        catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_b3ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
b2.setVisible(true);
b3.setVisible(false);
        i=0;
tf3.setVisible(true);
tf4.setVisible(true);
b1.setVisible(true);
b1.setVisible(true);
lb3.setVisible(true);
tf1.setText("");
tf2.setText("AO");
tf3.setText("");
tf4.setText("");
lb1.setIcon(null);
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
b3.setVisible(true);
b2.setVisible(false);
        i=1;
tf3.setVisible(false);
tf4.setVisible(false);
b1.setVisible(false);
b1.setVisible(false);
lb1.setIcon(null);
lb3.setVisible(false);
tf1.setText("");
tf2.setText("AO");
    }//GEN-LAST:event_rb2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
m=0;k=0; 
audio(32);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
setVisible(false);
audio(32);
java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_AS().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  setVisible(false);
audio(32);
java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGEMENT().setVisible(true);
            }
        });      // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
tf1.setText("");   
tf2.setText("AO"); 
tf3.setText(""); 
tf4.setText("");
audio(32);
lb1.setIcon(null);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tf3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf3FocusGained

    }//GEN-LAST:event_tf3FocusGained

    private void rb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb1MouseClicked
audio(32);
    }//GEN-LAST:event_rb1MouseClicked

    private void rb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb2MouseClicked
audio(32);       // TODO add your handling code here:
    }//GEN-LAST:event_rb2MouseClicked

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
this.setLocation(evt.getLocationOnScreen());        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ACCOUNT_OFFICE_M.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ACCOUNT_OFFICE_M.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ACCOUNT_OFFICE_M.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACCOUNT_OFFICE_M.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ACCOUNT_OFFICE_M().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb3;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
