/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_2;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import static library_2.LIBRARY_2.audio;
/**
 *
 * @author akash
 */
public class ACCOUNT_OFFICE extends javax.swing.JFrame {
byte h=0;
int sa=0;
byte fine=0;
byte d=0;
byte tfine=0;
byte w=0;
    /**
     * Creates new form ACCOUNT_OFFICE
     */
    public ACCOUNT_OFFICE() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(590, 300));
        setName("frame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(lb1);
        lb1.setBounds(10, 37, 330, 17);

        lb4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lb4);
        lb4.setBounds(460, 70, 70, 20);

        lb5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lb5.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lb5);
        lb5.setBounds(460, 20, 70, 20);

        lb2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(lb2);
        lb2.setBounds(10, 80, 370, 18);
        getContentPane().add(lb3);
        lb3.setBounds(210, 0, 120, 100);

        jLabel1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/turtle.png"))); // NOI18N
        jLabel1.setText("REGISTRATION NUMBER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 116, 200, 20);

        tf1.setBackground(new java.awt.Color(204, 204, 255));
        tf1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(222, 120, 330, 21);

        jLabel2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/stu.png"))); // NOI18N
        jLabel2.setText("NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 156, 80, 20);

        tf2.setBackground(new java.awt.Color(204, 204, 255));
        tf2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(tf2);
        tf2.setBounds(222, 160, 330, 21);

        jLabel3.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/books.png"))); // NOI18N
        jLabel3.setText("BOOK ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 196, 100, 20);

        tf3.setBackground(new java.awt.Color(204, 204, 255));
        tf3.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf3KeyTyped(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(222, 200, 330, 21);

        jLabel4.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/books.png"))); // NOI18N
        jLabel4.setText("BOOK NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 237, 130, 20);

        tf4.setBackground(new java.awt.Color(204, 204, 255));
        tf4.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(tf4);
        tf4.setBounds(222, 240, 330, 21);

        jButton11.setBackground(new java.awt.Color(102, 102, 102));
        jButton11.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/clear.png"))); // NOI18N
        jButton11.setText("CLEAR");
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(0, 280, 130, 20);

        jButton12.setBackground(new java.awt.Color(102, 102, 102));
        jButton12.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/exit.png"))); // NOI18N
        jButton12.setText("LOGOUT");
        jButton12.setBorder(null);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(290, 280, 130, 20);

        jButton13.setBackground(new java.awt.Color(102, 102, 102));
        jButton13.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/save.png"))); // NOI18N
        jButton13.setText("CLEAR DUES");
        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(140, 280, 140, 20);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton1.setText("UPDATE FINE LIST");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 280, 160, 20);

        jLabel6.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/money.png"))); // NOI18N
        jLabel6.setText("BOOK FINE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 20, 110, 20);

        jLabel7.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/money.png"))); // NOI18N
        jLabel7.setText("TOTAL FINE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 70, 120, 15);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/11.png"))); // NOI18N
        jLabel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel5MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 590, 310);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyReleased
      try
      {
        if(tf1.getText().contains("RA"))
        {
            if(tf1.getText().length()==15)
            {
                tf3.requestFocus();
                try{

                    ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from fine");
                    while(rs.next())
                    {
                        if(tf1.getText().equals(rs.getString("regestration_no")))
                        {
                            h=1;
                            tf2.setText(rs.getString("name"));

                        }
                    }
                }
                catch(Exception e)
                {
                }

                if(h==0)
                {
                    tf1.requestFocus();
                    audio(19);
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE ENTER THE VALID REGESTRATION NUMBER");
                    tf1.requestFocus();
                    tf1.setText("");
                    tf2.setText("");

                    h=0;
                    tf1.requestFocus();
                }
            }
        }
        else
        {
            if(tf1.getText().length()==15)
            {
                tf3.requestFocus();
                try{

                    ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from fine");
                    while(rs.next())
                    {
                        if(tf1.getText().equals(rs.getString("regestration_no")))
                        {
                            h=1;
                            tf2.setText(rs.getString("name"));

                        }
                    }
                }
                catch(Exception e)
                {
                }

                if(h==0)
                {
                    tf1.requestFocus();
                    audio(19);
                    javax.swing.JOptionPane.showMessageDialog(null, "PLEASE ENTER THE VALID REGESTRATION NUMBER");
                    tf1.requestFocus();
                    tf1.setText("");
                    tf2.setText("");

                    h=0;
                    tf1.requestFocus();
                }
            }
        }

try{

                    ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from fine");
                    while(rs.next())
                    {
                        if(tf1.getText().equals(rs.getString("regestration_no")))
                        {
                            tfine++;
                         
                        }
                    }
                    lb4.setText(""+tfine);
                    tfine=0;
}
catch(Exception e)
{
    
                        }  
      }
      catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_tf1KeyReleased

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped

    }//GEN-LAST:event_tf1KeyTyped

    private void tf3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyPressed

    }//GEN-LAST:event_tf3KeyPressed

    private void tf3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyReleased
try
{
        if(tf3.getText().length()==4)
        {
            try{
                tf3.requestFocus();
                ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from fine");
                while(rs.next())
                {
                    if(tf3.getText().equals(rs.getString("book_id")))
                    {
                        h=1;
                        tf4.setText(rs.getString("book_name"));

                    }
                }
            }
            catch(Exception e)
            {
            }

        }
        if(h==0 )
        {
            tf3.requestFocus();
            audio(8);
            javax.swing.JOptionPane.showMessageDialog(null, "PLEASE ENTER THE VALID BOOK_ID");

            tf3.setText("");
            tf4.setText("");

            h=0;

        }
try{

                    ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from fine");
                    while(rs.next())
                    {
                        if(tf1.getText().equals(rs.getString("regestration_no")) && Integer.parseInt(tf3.getText())==(rs.getInt("book_id")))
                        {
                            fine++;
                        }
                    }
                    lb5.setText(fine+"");
                    fine=0;
}
catch(Exception e)
{
    
                        }      
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_tf3KeyReleased

    private void tf3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyTyped

    }//GEN-LAST:event_tf3KeyTyped

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        tf1.setText(null);
        tf3.setText(null);
        tf4.setText(null);
        tf2.setText(null);
        audio(32);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
try
{
   audio(32);
    try
{
        String sql1 = "delete from temp_fine_record where book_id='"+tf3.getText()+"' and regestration_no = '"+tf1.getText()+"'";
PreparedStatement pst = null;
pst = LIBRARY_2.conn.prepareStatement(sql1);
pst.execute();
}
catch(Exception e)
{
    
}

            tf3.setText("");
            tf4.setText("");

        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_AS().setVisible(true);
            }
        });
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
try
{
    audio(32);
    if((tf1.getText().length()==0) || (tf2.getText().length()==0) || (tf3.getText().length()==0) || (tf4.getText().length()==0))
    {
        w=1;
        audio(29);
JOptionPane.showMessageDialog(null,"PLEASE FILL ALL THE  DETAILS");
    }
    if(w==0)
    {
        byte b=0;
        try
{
String s1=tf1.getText();
int s2=Integer.parseInt(tf3.getText());
ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from fine");
       while(rs.next())
       {
         int s3=rs.getInt("book_id");
         String s4=rs.getString("regestration_no");
         if(s2==s3 && s1.equals(s4))
         {
         try
{    
    b=1;
String sql1 = "delete from fine where book_id='"+Integer.parseInt(tf3.getText())+"' and regestration_no = '"+tf1.getText()+"'";
PreparedStatement pst = null;
pst = LIBRARY_2.conn.prepareStatement(sql1);
pst.execute();
}
catch(Exception e)
{

}
         if(d==0)
         {
audio(21);
JOptionPane.showMessageDialog(null,"DUES CLEARED SUCCESSFULLY");
tf3.setText("");
tf4.setText(""); 
d=1;
         }
         }
         
       }
       if(b==0)
       {
       audio(22);
JOptionPane.showMessageDialog(null,"PLEASE FILL THE CORRECT DETAILS");
tf1.setText("");
tf2.setText("");
tf3.setText("");
tf4.setText("");    
       }
   
}
catch(Exception e)
{
    
}
d=0;    
lb5.setText("0");
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
w=0;
    }//GEN-LAST:event_jButton13ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jButton11.setIconTextGap(40);
jButton12.setIconTextGap(30);
try
{
   
        lb4.setText("RS ");
lb5.setText("RS ");
        tf1.requestFocus();
audio(17);
try
{
String s1,s2,s3,s4;
s1=STUDENT_LOGIN_2.tf1.getText();
ImageIcon format;
 ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from AO_REG_NO");
       while(rs.next())
       {
           s2=rs.getString("REG_NO");
           s3=rs.getString("NAME");
           if(s1.equals(s2))
           {
               lb1.setText(s3);
               lb2.setText(STUDENT_LOGIN_2.tf1.getText());
               byte [] imagedata = rs.getBytes("pic");
    format = new ImageIcon(imagedata);
    lb3.setIcon(format);
           }
       }
}
catch (Exception e)
{
    
} 
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{
    audio(32);
    if(LIBRARY_2.upd==0)
    {
     try
        {
            Calendar cal = Calendar.getInstance();
         String a1=cal.getTime().toString().substring(0,10);

         ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from issued_book_details");
       while(rs.next())
       {
      String s=rs.getString("due_date").substring(0,10)  ;


       if (a1.equals(s))
       {

         PreparedStatement st = null;
st=LIBRARY_2.conn.prepareStatement("insert into fine(book_name,book_id,regestration_no,name,date) values(?,?,?,?,?)");
st.setString(1,rs.getString("book_name"));
st.setInt(2,rs.getInt("book_id"));
st.setString(3, rs.getString("regestration_no"));
st.setString(4,rs.getString("issued_to") );
st.setString(5, rs.getString("due_date"));
st.executeUpdate(); 
    
      
       }
       }
       audio(25);
JOptionPane.showMessageDialog(null, "LIST UPDATED SUCCESSFULLY");
LIBRARY_2.upd=1;
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,e.getMessage());
        } 
    }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseDragged
this.setLocation(evt.getLocationOnScreen());        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ACCOUNT_OFFICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ACCOUNT_OFFICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ACCOUNT_OFFICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ACCOUNT_OFFICE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ACCOUNT_OFFICE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    public static javax.swing.JTextField tf1;
    public static javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
