/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_2;

import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;
import static library_2.LIBRARY_2.audio;

/**
 *
 * @author akash
 */
public class BOOKS_M extends javax.swing.JFrame {
int ct=0;
byte k=0;
byte j=0;
    /**
     * Creates new form BOOKS_M
     */
    public BOOKS_M() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(525, 250));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/color.png"))); // NOI18N
        jButton5.setText("BACK");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 213, 250, 20);

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/exit.png"))); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(289, 213, 230, 20);

        jLabel1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jLabel1.setText("ADD BOOK");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 0, 116, 29);

        jLabel4.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/cross.png"))); // NOI18N
        jLabel4.setText("DELETE BOOK");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 0, 141, 29);

        jLabel2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/books.png"))); // NOI18N
        jLabel2.setText("BOOK ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 111, 18);

        jLabel3.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/books.png"))); // NOI18N
        jLabel3.setText("BOOK NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 116, 21);

        tf1.setBackground(new java.awt.Color(204, 204, 255));
        tf1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf1KeyReleased(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(140, 60, 120, 21);

        tf2.setBackground(new java.awt.Color(204, 204, 255));
        tf2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(tf2);
        tf2.setBounds(140, 110, 120, 21);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/save.png"))); // NOI18N
        jButton1.setText("ADD BOOK");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 150, 120, 26);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/clear.png"))); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 150, 120, 26);

        jLabel5.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/books.png"))); // NOI18N
        jLabel5.setText("BOOK ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 60, 99, 18);

        jLabel6.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/books.png"))); // NOI18N
        jLabel6.setText("BOOK NAME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 110, 111, 21);

        tf3.setBackground(new java.awt.Color(204, 204, 255));
        tf3.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf3KeyReleased(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(410, 60, 110, 30);

        tf4.setBackground(new java.awt.Color(204, 204, 255));
        tf4.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(tf4);
        tf4.setBounds(410, 110, 110, 30);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/cross.png"))); // NOI18N
        jButton3.setText("REMOVE");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 150, 111, 28);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/clear.png"))); // NOI18N
        jButton4.setText("CLEAR");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(408, 150, 110, 26);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/Untitled4.png"))); // NOI18N
        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 540, 250);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
setVisible(false);
audio(32);
 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MANAGEMENT().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
setVisible(false);
audio(32);
 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_AS().setVisible(true);
            }
        });       // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
tf1.setText("");
tf2.setText("");
audio(32);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
tf3.setText("");
tf4.setText("");
audio(32);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tf1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyReleased
if(tf1.getText().length()==4)
{
    tf2.requestFocus();
}
if(tf1.getText().length()>4)
{
    JOptionPane.showMessageDialog(null,"PLEAS ENTER 4 DIGIT NUMBER");  
    tf1.setText(null);
}
    }//GEN-LAST:event_tf1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try
 {
     audio(32);
        int m=0;
        if(tf1.getText().length()==0 || tf2.getText().length()==0)
   
{
 m=1;   
}
        if(m==0)
        {
        try
{
ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from books");
    while(rs.next())
       {
         if(Integer.parseInt(tf1.getText())==rs.getInt("b_id"))
         {
             k=1;
audio(8);
             JOptionPane.showMessageDialog(null,"PLEASE ENTER THE VALID BOOK ID");
             tf1.setText("");
             tf2.setText("");
         }
       }     
}
catch(Exception e)
{
    
}
if(k==0)
{
        try
{
ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from books");
    while(rs.next())
       {
         ct=rs.getInt("s_no");
       } 
int bid = Integer.parseInt(tf1.getText());
String bname = tf2.getText();
PreparedStatement st = null;
st=LIBRARY_2.conn.prepareStatement("insert into books(s_no,b_id,book_name,status) values(?,?,?,?)");
st.setInt(1,(++ct));
st.setInt(2, bid);
st.setString(3, bname);
st.setString(4,"AVAILABLE");
st.executeUpdate();
audio(18); 
JOptionPane.showMessageDialog(null, "DATA SAVED SUCCESSFULLY");
  tf1.setText(null);
             tf2.setText(null);
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,e.getMessage())   ;
e.printStackTrace();
}
}
        }
        if(m==1)
{
audio(29);
    JOptionPane.showMessageDialog(null,"PLEASE FILL ALL THE DETAILS");
    
}
k=0;
 }
 catch(Exception e)
 {
     JOptionPane.showMessageDialog(null,e.getMessage());
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
audio(17); 
jButton2.setIconTextGap(20);
jButton5.setIconTextGap(90);
jButton6.setIconTextGap(60);
jButton4.setIconTextGap(15);
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try
{
    audio(32);
        int n=0;
if((tf3.getText().length()==0) || (tf4.getText().length()==0))
{
    n=1;
}
if(n==1)
{
audio(29);
    JOptionPane.showMessageDialog(null,"PLEASE FILL ALL THE DETAILS");
    
}
if(n==0)
{
        try
{
ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from books");
    while(rs.next())
       {
         if(Integer.parseInt(tf3.getText())==rs.getInt("b_id"))
         {
             j=1;
         }
       }
}
catch(Exception e)
{
    
}
if(j==1)
{
        try
{
String sql = "delete from books where b_id='"+Integer.parseInt(tf3.getText())+"'";
PreparedStatement pst = null;
pst =LIBRARY_2.conn.prepareStatement(sql);
pst.execute();
audio(30);
JOptionPane.showMessageDialog(null, "DATA DELETED SUCCESSFULLY");
  tf3.setText(null);
             tf4.setText(null);
}   
catch(Exception e)
{
JOptionPane.showMessageDialog(null, e.getMessage());
e.printStackTrace();
}
}
if(j==0)
{
audio(8);
             JOptionPane.showMessageDialog(null,"PLEASE ENTER THE VALID BOOK ID");  
             tf3.setText(null);
             tf4.setText(null);
    
}
}
   
j=0;
}
catch(Exception e)
 {
     JOptionPane.showMessageDialog(null,e.getMessage());
 }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tf3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyReleased
try
{
        if(tf3.getText().length()==4)
{
    tf4.requestFocus();
    try
    {
     ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from books");
    while(rs.next())
       {
         if(Integer.parseInt(tf3.getText())==rs.getInt("b_id"))
         {
           tf4.setText(rs.getString("book_name"));
         }
       }   
    }
    catch(Exception f)
    {
        
    }
}
if(tf3.getText().length()>4)
{
    JOptionPane.showMessageDialog(null,"PLEAS ENTER 4 DIGIT NUMBER");  
    tf3.setText(null);
    tf4.setText(null);
}
}
catch(Exception e)
 {
     JOptionPane.showMessageDialog(null,e.getMessage());
 }
    }//GEN-LAST:event_tf3KeyReleased

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
this.setLocation(evt.getLocationOnScreen());        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOKS_M.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOKS_M.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOKS_M.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOKS_M.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BOOKS_M().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
