/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_2;

import java.awt.Toolkit;
import static library_2.LIBRARY_2.audio;

/**
 *
 * @author akash
 */
public class DEVELOPER extends javax.swing.JFrame {

    /**
     * Creates new form DEVELOPER
     */
    public DEVELOPER() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setMaximumSize(new java.awt.Dimension(477, 208));
        setMinimumSize(new java.awt.Dimension(477, 208));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel1.setText("DEVELOPER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 170, 18);

        jLabel2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel2.setText("CONTACT INFO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 150, 114, 15);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/exit.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 180, 410, 20);

        jLabel3.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel3.setText("COLLEGE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 30, 77, 18);

        jLabel4.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel4.setText("COURSE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 110, 80, 15);

        jLabel5.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel5.setText("SECTION");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 130, 81, 15);

        jLabel6.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel6.setText("REGISTraTION NUMBER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 50, 210, 18);

        jLabel7.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel7.setText("YEAR");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 70, 49, 18);

        jLabel8.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel8.setText("SEMESTER");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 90, 100, 18);

        jLabel9.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel9.setText("AKASH TRIPTHI");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 10, 150, 18);

        jLabel10.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel10.setText("SRM");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(270, 30, 150, 18);

        jLabel11.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel11.setText("RA1511003030444");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(270, 50, 180, 18);

        jLabel12.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel12.setText("SECOND");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(270, 70, 68, 18);

        jLabel13.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel13.setText("FOUR");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 90, 47, 15);

        jLabel14.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel14.setText("CSE");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(270, 110, 38, 18);

        jLabel15.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel15.setText("H");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(270, 130, 20, 18);

        jLabel16.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jLabel16.setText("kumarakash1997.t@gmail.com");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(190, 150, 280, 15);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/1.png"))); // NOI18N
        jLabel17.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel17MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 480, 210);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
audio(32);
java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_AS().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
audio(32);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jLabel17MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseDragged
this.setLocation(evt.getLocationOnScreen());        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEVELOPER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEVELOPER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEVELOPER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEVELOPER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEVELOPER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
