/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_2;

import java.awt.Toolkit;
import java.sql.*;
import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;
import static library_2.LIBRARY_2.audio;

/**
 *
 * @author akash
 */
public class ISSUE extends javax.swing.JFrame {
   public static byte c=0;
byte h=0;
int sas=0;
byte d=0;
public static boolean g =false;
   static int sa=0;
   public static byte bcount=0;
    public void count(byte d)
    {
        if(d==4)
        {
        try{
              
       ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from books");
       while(rs.next())
       {
           if(tf1.getText().equals(rs.getString("b_id")))
           {
               h=1;
               tf2.setText(rs.getString("book_name"));
              
           }
       }
        }
       catch(Exception e)
               {
               }
        
        }
        if(h==0 && d==4)
       {
           tf1.requestFocus();
audio(8);
            javax.swing.JOptionPane.showMessageDialog(null, "PLEASE ENTER THE VALID BOOK_ID");
       tf1.requestFocus();
       tf1.setText("");
       tf2.setText("");
       c=0;
       h=0;
       tf1.requestFocus();
        }
    }
    
    public void count1(byte e)
    {
     if(e>4)   
     {
audio(8);
            javax.swing.JOptionPane.showMessageDialog(null, "PLEASE ENTER THE VALID BOOK_ID");
       tf1.setText("");
       tf2.setText("");
       c=0;
          tf1.requestFocus();
     }
    }

    /**
     * Creates new form ISSUE
     */
    public ISSUE() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        tf2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(702, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(702, 225));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/books.png"))); // NOI18N
        jLabel1.setText("BOOK ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(73, 8, 100, 18);

        tf1.setBackground(new java.awt.Color(204, 204, 255));
        tf1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(tf1);
        tf1.setBounds(10, 37, 207, 21);

        jLabel2.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/books.png"))); // NOI18N
        jLabel2.setText("BOOK NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(86, 169, 130, 18);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton1.setText("1");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 64, 67, 18);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton2.setText("2");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(83, 64, 63, 18);

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton3.setText("3");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(156, 64, 60, 18);

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton4.setText("4");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 89, 67, 18);

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton5.setText("5");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(83, 89, 63, 18);

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton6.setText("6");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(156, 89, 60, 18);

        jButton7.setBackground(new java.awt.Color(153, 153, 153));
        jButton7.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton7.setText("7");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 114, 67, 18);

        jButton8.setBackground(new java.awt.Color(153, 153, 153));
        jButton8.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton8.setText("8");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(83, 114, 63, 19);

        jButton9.setBackground(new java.awt.Color(153, 153, 153));
        jButton9.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton9.setText("9");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(156, 114, 60, 18);

        jButton10.setBackground(new java.awt.Color(153, 153, 153));
        jButton10.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/write.png"))); // NOI18N
        jButton10.setText("0");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(83, 139, 63, 18);

        b1.setBackground(new java.awt.Color(153, 153, 153));
        b1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/save.png"))); // NOI18N
        b1.setText("ISSUE");
        b1.setBorder(null);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(222, 38, 128, 19);

        jButton13.setBackground(new java.awt.Color(153, 153, 153));
        jButton13.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/clear.png"))); // NOI18N
        jButton13.setText("CLEAR");
        jButton13.setBorder(null);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(220, 80, 129, 19);

        jButton14.setBackground(new java.awt.Color(153, 153, 153));
        jButton14.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/color.png"))); // NOI18N
        jButton14.setText("BACK");
        jButton14.setBorder(null);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(220, 120, 130, 19);

        jButton15.setBackground(new java.awt.Color(153, 153, 153));
        jButton15.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/exit.png"))); // NOI18N
        jButton15.setText("LOGOUT");
        jButton15.setBorder(null);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(220, 160, 129, 19);

        ta1.setBackground(new java.awt.Color(204, 204, 255));
        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(351, 37, 350, 180);

        tf2.setBackground(new java.awt.Color(204, 204, 255));
        tf2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(10, 193, 318, 21);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/Untitledak.png"))); // NOI18N
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 760, 230);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
tf1.setText(tf1.getText()+"1");
c++;
count(c);
count1(c);
audio(32);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
tf1.setText(tf1.getText()+"2");
c++;
count(c);    
count1(c);
audio(32);
audio(32);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
tf1.setText(tf1.getText()+"3");
c++;
count(c);  
count1(c);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
tf1.setText(tf1.getText()+"4");
c++;
count(c); 
count1(c);
audio(32);
audio(32);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
tf1.setText(tf1.getText()+"5");
c++;
count(c); 
count1(c);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
tf1.setText(tf1.getText()+"6");
c++;
count(c);
count1(c);
audio(32);// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
tf1.setText(tf1.getText()+"7");
c++;
count(c);
count1(c);
audio(32);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
tf1.setText(tf1.getText()+"8");
c++;
count(c);
count1(c);
audio(32);
// TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
tf1.setText(tf1.getText()+"9");
c++;
count(c);    
count1(c);
audio(32);// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
tf1.setText(tf1.getText()+"0");
c++;
count(c);   
count1(c);
audio(32);// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
audio(32);
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_AS().setVisible(true);
            }
        });    
        c=0;// TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
setVisible(false);
audio(32);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SELECT().setVisible(true);
            }
        });   
        c=0;// TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
audio(7);
jButton14.setIconTextGap(25);
jButton13.setIconTextGap(20);
b1.setIconTextGap(25);
    }//GEN-LAST:event_formWindowOpened

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
tf1.setText(null);
tf2.setText(null); 
c=0;
audio(32);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
try
{
    audio(32);
        byte k =0;
{
    try
    {
    String s1 = STUDENT_LOGIN_2.tf1.getText();
    int s2 = Integer.parseInt(tf1.getText());
    ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from book_record");
    while(rs.next())
       {
         String  s3=rs.getString("reg_no");
          int s4=rs.getInt("b_id");
         if(s1.equals(s3)&& s2==s4)
           {
           k=1;
           
           }
       }
    }
    catch(Exception e)
    {
        
    }
}
if(k==1)
{
        byte z=0;
        try
{
String s1 = STUDENT_LOGIN_2.tf1.getText();
 ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from fine");
 while(rs.next())
       {
         String  s3=rs.getString("regestration_no");
         if(s1.equals(s3))
           {
           z=1;  
           if(d==0)
           {
audio(23);
    JOptionPane.showMessageDialog(null, "FIRST CLEAR YOUR DUES");
tf1.setText(null);
tf2.setText("");
c=0;
d=1;
           }
           }
       }
 
}
catch (Exception e)
{
    
           }
        if(z==0)
        {
        Calendar cal = Calendar.getInstance();
        Calendar cal1 = Calendar.getInstance();

        
        
 byte b=0;
    byte d=5;
    int a =0;
    h=0;
    byte f=5;
  
        if (c < 4)
{
audio(8);
    JOptionPane.showMessageDialog(null, "PLEASE ENTER THE VALID BOOK_ID");
tf1.setText(null);
tf2.setText("");
c=0;
}
else
{
 
        try{
           String s1,s2,s3,s4;

           s1=STUDENT_LOGIN_2.tf1.getText();
           s2="ISSUED";
           String s5="RENEWED";
       ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from issued_book_details");
       while(rs.next())
       {
           s3=rs.getString("registration_no");
           s4=rs.getString("type");
           
           if(s1.equals(s3)&& (s4.equals(s2) || s4.equals(s5)))
           {
 ResultSet rs1=LIBRARY_2.stmt.executeQuery("select * from issued_book_details where regestration_no='"+STUDENT_LOGIN_2.tf1.getText()+"' and type='issued' or type='renewed'");
 while (rs1.next())
 {
       bcount++;     
 }
 a=bcount;               
bcount=0;       
           }
       }
       }
       catch(Exception e)
       {
       }
        if (a<5)
        {
try{

           String s1,s2,s4;
           String s3="AVAILABLE";
           s1=tf1.getText();
       ResultSet rs1=LIBRARY_2.stmt.executeQuery("select * from books");
       while(rs1.next())
       {
           s2=rs1.getString("b_id");
           s4=rs1.getString("status");
           if(s4.equals(s3) && s1.equals(s2))
             
           {
b=1;
d=1;
h=1;
               
try
{
 String s9="UNAVAILABLE";       
String sql = "update books set status='"+s9+"' where b_id='"+tf1.getText()+"'";
PreparedStatement pst = null;
pst = LIBRARY_2.conn.prepareStatement(sql);
pst.execute();
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,e.getMessage());
}

 ta1.append("\n-------------------------------------------------------------------------------");
ta1.append("\n COLLEGE                            :  SRM NCR");
ta1.append("\n SERIAL NUMBER               :  " +(++sas));
ta1.append("\n BOOK ISSUED TO              : "+SELECT.lb1.getText().replaceFirst("WELCOME",""));
ta1.append("\n REGISTRATION NO          :  "+STUDENT_LOGIN_2.tf1.getText());
ta1.append("\n BOOK NAME                        :  "+tf2.getText());  
ta1.append("\n BOOK ID                               :  "+tf1.getText());      
ta1.append("\n ISSUE DATE                        :  "+cal.getTime());
cal.add(Calendar.DATE, 15);
String a1=cal.getTime().toString();
cal1.add(Calendar.DATE, 14);
String a2=cal1.getTime().toString();
ta1.append("\n DUE DATE                           :  "+a2);
ta1.append("\n------------------------ISSUE SUCCESSFULL--------------------------");
ta1.append("\n-------------------------------------------------------------------------------");
c=0;

 try{
            
              ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from issued_book_details");
       while(rs.next())
       {
         sa=rs.getInt("s_no");
       }
 
        String reg= STUDENT_LOGIN_2.tf1.getText();
String name = SELECT.lb1.getText().replaceFirst("WELCOME", "");
String bid = tf1.getText();
String bname = tf2.getText();
PreparedStatement st = null;
st=LIBRARY_2.conn.prepareStatement("insert into issued_book_details(s_no,issued_to,book_name,book_id,regestration_no,date,time,type,due_date) values(?,?,?,?,?,?,?,?,?)");
st.setInt(1,(++sa));
st.setString(2, name);
st.setString(3, bname);
st.setString(4, bid);
st.setString(5, reg);
java.sql.Date sqldate = new java.sql.Date(new java.util.Date().getTime());
st.setDate(6, sqldate);
java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());
st.setTimestamp(7, date);
st.setString(8, "ISSUED");
st.setString(9,a1 );
st.executeUpdate();
        }
        catch(Exception e)
        {
       
        }
audio(13);
try{
            
              ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from renewed_book_details");
       while(rs.next())
       {
         sa=rs.getInt("s_no");
       }
        String reg= STUDENT_LOGIN_2.tf1.getText();
String name = SELECT.lb1.getText().replaceFirst("WELCOME", "");
String bid = tf1.getText();
String bname = tf2.getText();
PreparedStatement st = null;
st=LIBRARY_2.conn.prepareStatement("insert into renewed_book_details(s_no,renewed_by,book_name,book_id,regestration_no,date,time,type) values(?,?,?,?,?,?,?,?)");
st.setInt(1,(sa));
st.setString(2, name);
st.setString(3, bname);
st.setString(4, bid);
st.setString(5, reg);
java.sql.Date sqldate = new java.sql.Date(new java.util.Date().getTime());
st.setDate(6, sqldate);
java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());
st.setTimestamp(7, date);
st.setString(8, "RENEWED");
st.executeUpdate();
        }
        catch(Exception e)
        {
       
        }
}
           
               
       }
       if(h==0)
               {
audio(10);
            JOptionPane.showMessageDialog(null,"SORRY, THIS BOOK IS ALREADY ISSUED");
        tf1.setText("");
        tf2.setText("");
        g=true; 
               }          
 
       c=0;
       }
       catch(Exception e)
       {
        
       }   
     }
       else
        {
audio(11); 
            JOptionPane.showMessageDialog(null,"YOU CAN'T ISSUE MORE THAN 5 BOOKS");
        }
        tf1.setText("");
        tf2.setText("");
        g=true;
    }
     c=0;
   h=0;
        }
}
if(k==0)
{
audio(26);
    JOptionPane.showMessageDialog(null, "YOU ARE NOT A VALID USER");
tf1.setText(null);
tf2.setText("");
c=0;
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
d=0;
    }//GEN-LAST:event_b1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed

    }//GEN-LAST:event_tf2ActionPerformed

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
this.setLocation(evt.getLocationOnScreen());        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISSUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISSUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISSUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISSUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISSUE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
