/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_2;


import java.awt.Toolkit;
import java.sql.*;
import javax.swing.ImageIcon;
import java.util.Calendar;
import javax.swing.JOptionPane;
import static library_2.LIBRARY_2.audio;
/**
 *
 * @author akash
 */
public class MY_ACCOUNT extends javax.swing.JFrame {
public static String s9;
    /**
     * Creates new form MY_ACCOUNT
     */
    public MY_ACCOUNT() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        lb3 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setMinimumSize(new java.awt.Dimension(560, 515));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/color.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 488, 245, 20);

        ta1.setBackground(new java.awt.Color(204, 204, 255));
        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 106, 533, 373);
        getContentPane().add(lb3);
        lb3.setBounds(411, 11, 132, 77);

        lb1.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(lb1);
        lb1.setBounds(10, 28, 252, 16);

        lb2.setFont(new java.awt.Font("DigifaceWide", 3, 12)); // NOI18N
        getContentPane().add(lb2);
        lb2.setBounds(10, 62, 252, 20);

        jButton2.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/exit.png"))); // NOI18N
        jButton2.setText("LOGOUT");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(294, 488, 249, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/2.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false) ;
audio(32);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SELECT().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try
{
audio(16);
if(LOGIN_AS.c==1)
{
try
{
String s1,s2,s3,s4;
s1=STUDENT_LOGIN_2.tf1.getText();
ImageIcon format;
 ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from STUDENT_REG_NO");
       while(rs.next())
       {
           s2=rs.getString("REG_NO");
           s3=rs.getString("NAME");
           if(s1.equals(s2))
           {
               lb1.setText(s3);
               lb2.setText(STUDENT_LOGIN_2.tf1.getText());
               byte [] imagedata = rs.getBytes("pic");
    format = new ImageIcon(imagedata);
    lb3.setIcon(format);
           }
       }
}
catch (Exception e)
{
    
}
}
if(LOGIN_AS.c==2)
{
try
{
String s1,s2,s3,s4;
s1=STUDENT_LOGIN_2.tf1.getText();
ImageIcon format;
 ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from TEACHER_REG_NO");
       while(rs.next())
       {
           s2=rs.getString("REG_NO");
           s3=rs.getString("NAME");
           if(s1.equals(s2))
           {
               lb1.setText(s3);
               lb2.setText(STUDENT_LOGIN_2.tf1.getText());
               byte [] imagedata = rs.getBytes("pic");
    format = new ImageIcon(imagedata);
    lb3.setIcon(format);
           }
       }
}
catch (Exception e)
{
    
}
}
byte sa=0;
try
{
    String s1=lb2.getText();
ResultSet rs=LIBRARY_2.stmt.executeQuery("select date from issued_book_details where regestration_no='"+s1+"' and type = 'ISSUED' or type = 'RENEWED'"); 
while(rs.next())
{
    Date s2=rs.getDate("date");
    String s3=rs.getString("regestration_no");
    if(s1.equals(s3))
    {

    }
}

}
catch(Exception e)
{
    
}
try
{
String s1,s2,s3,s4,s5,s6;
String s7;
int s8=0;
s1=lb2.getText();
s2="ISSUED";
s3="RENEWED";
 ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from issued_book_details where regestration_no='"+s1+"' and type = 'ISSUED' or type = 'RENEWED'");
       while(rs.next())
       {
           sa++;
           s4=rs.getString("REGESTRATION_NO");
           s5=rs.getString("type");
           s6=rs.getString("book_name");
           s7=rs.getDate("date").toString();
            s9=rs.getString("due_date");
           s8=rs.getInt("book_id");
           if(s1.equals(s4) &&((s5.equals(s2))|| (s5.equals(s3)))  )
           {
ta1.append("\n-------------------------------------------------------------------------------");
ta1.append("\n SERIAL NUMBER               :  " +(sa));
ta1.append("\n BOOK NAME                        :  "+(s6));  
ta1.append("\n BOOK ID                               :  "+(s8));      
ta1.append("\n ISSUE DATE                        :  "+s7);
ta1.append("\n DUE DATE                           :  "+s9);
ta1.append("\n-------------------------------INFORMATION--------------------------");
ta1.append("\n-------------------------------------------------------------------------------");
           }
       }
}
catch(Exception e)
{
    
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
audio(32);
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_AS().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
this.setLocation(evt.getLocationOnScreen());        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MY_ACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MY_ACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MY_ACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MY_ACCOUNT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MY_ACCOUNT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
