/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_2;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static library_2.LIBRARY_2.audio;

/**
 *
 * @author akash
 */
public class SELECT extends javax.swing.JFrame {
byte tfine=0;
    /**
     * Creates new form SELECT
     */
    public SELECT() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        lb3 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(400, 180));
        setMinimumSize(new java.awt.Dimension(515, 270));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/stu.png"))); // NOI18N
        jButton1.setText("ISSUE");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 56, 270, 20);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/stu.png"))); // NOI18N
        jButton2.setText("RENEW");
        jButton2.setBorder(null);
        jButton2.setMaximumSize(new java.awt.Dimension(37, 15));
        jButton2.setMinimumSize(new java.awt.Dimension(37, 15));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 90, 270, 20);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/stu.png"))); // NOI18N
        jButton3.setText("RETURN");
        jButton3.setBorder(null);
        jButton3.setMaximumSize(new java.awt.Dimension(37, 15));
        jButton3.setMinimumSize(new java.awt.Dimension(37, 15));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 124, 270, 20);

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/stu.png"))); // NOI18N
        jButton4.setText("MY ACCOUNT");
        jButton4.setBorder(null);
        jButton4.setMaximumSize(new java.awt.Dimension(37, 15));
        jButton4.setMinimumSize(new java.awt.Dimension(37, 15));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 158, 270, 20);

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/exit.png"))); // NOI18N
        jButton7.setText("LOGOUT");
        jButton7.setBorder(null);
        jButton7.setMaximumSize(new java.awt.Dimension(37, 15));
        jButton7.setMinimumSize(new java.awt.Dimension(37, 15));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 195, 270, 20);

        lb1.setFont(new java.awt.Font("DigifaceWide", 3, 14)); // NOI18N
        getContentPane().add(lb1);
        lb1.setBounds(20, 20, 470, 20);
        getContentPane().add(lb2);
        lb2.setBounds(340, 110, 140, 130);

        b1.setBackground(new java.awt.Color(102, 102, 102));
        b1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/greenfile.png"))); // NOI18N
        b1.setText("CHANGE PASSWORD");
        b1.setBorder(null);
        b1.setMaximumSize(new java.awt.Dimension(37, 15));
        b1.setMinimumSize(new java.awt.Dimension(37, 15));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(10, 225, 270, 20);

        lb3.setFont(new java.awt.Font("DigifaceWide", 2, 18)); // NOI18N
        lb3.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(lb3);
        lb3.setBounds(440, 60, 50, 20);

        lb5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lb5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/money.png"))); // NOI18N
        lb5.setText("FINE  Rs");
        getContentPane().add(lb5);
        lb5.setBounds(340, 60, 90, 20);
        getContentPane().add(lb6);
        lb6.setBounds(0, 0, 510, 20);
        getContentPane().add(lb7);
        lb7.setBounds(0, 250, 500, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/library_2/1111.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 270);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);
audio(32);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISSUE().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try
{
jButton1.setIconTextGap(100);
jButton2.setIconTextGap(95);
jButton3.setIconTextGap(90);
jButton4.setIconTextGap(60);
jButton7.setIconTextGap(80);
b1.setIconTextGap(10);
        try{

                    ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from fine");
                    while(rs.next())
                    {
                        if(STUDENT_LOGIN_2.tf1.getText().equals(rs.getString("regestration_no")))
                        {
                            tfine++;
                         
                        }
                    }
                    if(tfine==0)
                    {
                         lb7.setText("x---------------------------------------------x---------------------------------------------x");
                            lb6.setText("x---------------------------------------------x---------------------------------------------x");
                            lb6.setForeground(Color.green);
                            lb7.setForeground(Color.green);   
                        lb5.setForeground(Color.green);
                        lb3.setForeground(Color.green);
                        lb5.setText("NO FINE");
                        lb3.setVisible(false);
                    }
                    else
                    {
                            lb7.setText("x---------------------------------------------x---------------------------------------------x");
                            lb6.setText("x---------------------------------------------x---------------------------------------------x");
                            lb6.setForeground(Color.red);
                            lb7.setForeground(Color.red);            
                    
                        lb5.setForeground(Color.red);                      
                        lb3.setForeground(Color.red);
                    lb3.setText(""+tfine);   
                        
                    }
                    tfine=0;
}
catch(Exception e)
{
    
                        }  
 
        if(LOGIN_AS.c==1)
{
        try{
String s1,s2;
s1=STUDENT_LOGIN_2.tf1.getText();
        ImageIcon format;
       ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from student_reg_no");
       while(rs.next())
       {
           s2=rs.getString("reg_no");
           if(s1.equals(s2))
           {
            byte [] imagedata = rs.getBytes("pic");
    format = new ImageIcon(imagedata);
    lb2.setIcon(format);
           }
       }
       }
       catch(Exception e)
       {
       }
}
        
String s;
audio(6);
        if(LOGIN_AS.c==1)
{
        try{
           String s1,s2;
           s1=STUDENT_LOGIN_2.tf1.getText();
        Statement stmt;
       ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from STUDENT_REG_NO");
       while(rs.next())
       {
           s2=rs.getString("REG_NO");
           if(s1.equals(s2))
           {
s=rs.getString("NAME");
lb1.setText("WELCOME  "+s);
           }
       }
        }
catch(Exception e){
        
        }
}
        
        if(LOGIN_AS.c==2)
{
        try{
String s1,s2;
s1=STUDENT_LOGIN_2.tf1.getText();
        ImageIcon format;
       ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from teacher_reg_no");
       while(rs.next())
       {
           s2=rs.getString("reg_no");
           if(s1.equals(s2))
           {
            byte [] imagedata = rs.getBytes("pic");
    format = new ImageIcon(imagedata);
    lb2.setIcon(format);
           }
       }
       }
       catch(Exception e)
       {
       }
}
if(LOGIN_AS.c==2)
{
       
        try{
           String s1,s2;
           s1=STUDENT_LOGIN_2.tf1.getText();
        Statement stmt;
       ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from TEACHER_REG_NO");
       while(rs.next())
       {
           s2=rs.getString("REG_NO");
           if(s1.equals(s2))
           {
s=rs.getString("NAME");
lb1.setText("WELCOME  "+s);
           }
       }
        }
catch(Exception e){
        
        }
}
if(LOGIN_AS.c==3)
{
        
        try{
           String s1,s2;
           s1=STUDENT_LOGIN_2.tf1.getText();
        Statement stmt;
     
       ResultSet rs=LIBRARY_2.stmt.executeQuery("select * from INCHARGE_REG_NO");
       while(rs.next())
       {
           s2=rs.getString("REG_NO");
           if(s1.equals(s2))
           {
s=rs.getString("NAME");
lb1.setText("WELCOME  "+s);
           }
       }
        }
catch(Exception e){
        
        }
}
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}
    }//GEN-LAST:event_formWindowOpened

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
audio(32);
        setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_AS().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
setVisible(false);
audio(32);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RETURN().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
setVisible(false);
audio(32);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RENEW().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
setVisible(false);
audio(32);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MY_ACCOUNT().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
setVisible(false);
audio(32);
 java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PASSWORD().setVisible(true);
            }
        });
    }//GEN-LAST:event_b1ActionPerformed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
this.setLocation(evt.getLocationOnScreen());        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SELECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SELECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SELECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SELECT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SELECT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
