/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3.player;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author akash
 */
public class input_dialog extends javax.swing.JDialog {
   public static String pname = null;

    /**
     * Creates new form input_dialog
     */
    public input_dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
        input.setBackground(new Color(0,0,0,0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cross = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        loc = new javax.swing.JLabel();
        ok = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cross.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/on.png"))); // NOI18N
        cross.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cross.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                crossMouseMoved(evt);
            }
        });
        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crossMouseReleased(evt);
            }
        });
        getContentPane().add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 50, 20));

        input.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        input.setForeground(new java.awt.Color(204, 204, 204));
        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.setBorder(null);
        input.setOpaque(false);
        input.setSelectionColor(new java.awt.Color(0, 102, 255));
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, 170, -1));

        loc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/icon.png"))); // NOI18N
        loc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                locMouseDragged(evt);
            }
        });
        loc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                locMousePressed(evt);
            }
        });
        getContentPane().add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okMouseReleased(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 110, 10));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/input.png"))); // NOI18N
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 260, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void locMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMouseDragged

    }//GEN-LAST:event_locMouseDragged

    private void locMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMouseClicked

    }//GEN-LAST:event_locMouseClicked

    private void locMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMousePressed

    }//GEN-LAST:event_locMousePressed

    private void crossMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseMoved
        //cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
    }//GEN-LAST:event_crossMouseMoved

    private void crossMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseReleased
        try
        {
            new Thread()
            {
                public void run()
                {
                    cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/off1.png")));
                }
            }.start();
            new Thread()
            {
                public void run()
                {
                    try {
                        Thread.sleep(1000);
                        
                    } catch (InterruptedException ex) {
                    }
                }
            }.start();
            this.dispose();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_crossMouseReleased

    private void okMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseReleased
pname = input.getText();
this.dispose();
    }//GEN-LAST:event_okMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input_dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input_dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input_dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input_dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                input_dialog dialog = new input_dialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cross;
    private javax.swing.JLabel img;
    private javax.swing.JTextField input;
    private javax.swing.JLabel loc;
    private javax.swing.JLabel ok;
    // End of variables declaration//GEN-END:variables
}
