/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3.player;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static mp3.player.CJOptionPane.c;

/**
 *
 * @author akash
 */
public class JOptionPane extends javax.swing.JDialog {

    /**
     * Creates new form JOptionPane1
     */
    public JOptionPane(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    JOptionPane() {
        try {
            initComponents();
            setBackground(new Color(0,0,0,0));
            int x = 0,y = 0;  
            ResultSet rs=DB.stmt.executeQuery("select * from loc");
            while(rs.next())
            {
                x=rs.getInt("x");
                y=rs.getInt("y");       
            }
            this.setLocation(x-10,y-10);
            //  this.setLocation(lastX, lastY);
        
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        } catch (SQLException ex) {
            Logger.getLogger(JOptionPane.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cross = new javax.swing.JLabel();
        ok1 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        loc = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        ok = new javax.swing.JLabel();
        que = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setFocusCycleRoot(false);
        setFocusableWindowState(false);
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cross.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/on.png"))); // NOI18N
        cross.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cross.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                crossMouseMoved(evt);
            }
        });
        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crossMouseReleased(evt);
            }
        });
        getContentPane().add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 50, 20));

        ok1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ok1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ok1MouseReleased(evt);
            }
        });
        getContentPane().add(ok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 110, 10));

        input.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        input.setForeground(new java.awt.Color(204, 204, 204));
        input.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        input.setText("playlist1");
        input.setBorder(null);
        input.setDoubleBuffered(true);
        input.setDragEnabled(true);
        input.setFocusCycleRoot(true);
        input.setFocusTraversalPolicyProvider(true);
        input.setInheritsPopupMenu(true);
        input.setOpaque(false);
        input.setSelectionColor(new java.awt.Color(0, 102, 255));
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, 170, -1));

        loc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/icon.png"))); // NOI18N
        loc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                locMouseDragged(evt);
            }
        });
        loc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                locMousePressed(evt);
            }
        });
        getContentPane().add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/input.png"))); // NOI18N
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 260, 70));

        ok.setFont(new java.awt.Font("Arabic Typesetting", 2, 24)); // NOI18N
        ok.setForeground(new java.awt.Color(255, 255, 255));
        ok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ok.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                okMouseMoved(evt);
            }
        });
        ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okMouseClicked(evt);
            }
        });
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 130, 30));

        que.setFont(new java.awt.Font("Bell MT", 0, 13)); // NOI18N
        que.setForeground(new java.awt.Color(204, 204, 204));
        que.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(que, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 40));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/jop2.png"))); // NOI18N
        img.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                imgMouseDragged(evt);
            }
        });
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgMousePressed(evt);
            }
        });
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -30, 270, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseClicked
        c=1;
        this.dispose();
    }//GEN-LAST:event_okMouseClicked

    private void imgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseDragged

    }//GEN-LAST:event_imgMouseDragged

    private void imgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMousePressed

    }//GEN-LAST:event_imgMousePressed

    private void locMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMouseDragged

    }//GEN-LAST:event_locMouseDragged

    private void locMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMouseClicked

    }//GEN-LAST:event_locMouseClicked

    private void locMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMousePressed

    }//GEN-LAST:event_locMousePressed

    private void okMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_okMouseMoved

    private void ok1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok1MouseReleased
        c=1;
        this.dispose();
    }//GEN-LAST:event_ok1MouseReleased

    private void crossMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseMoved
        //cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
    }//GEN-LAST:event_crossMouseMoved

    private void crossMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseReleased
        try
        {
            new Thread()
            {
                public void run()
                {
                    cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/off1.png")));
                }
            }.start();
            new Thread()
            {
                public void run()
                {
                    try {
                        Thread.sleep(1000);

                    } catch (InterruptedException ex) {
                    }
                }
            }.start();
            c=1;
            this.dispose();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_crossMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JOptionPane dialog = new JOptionPane(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel cross;
    public static javax.swing.JLabel img;
    public static javax.swing.JLabel img1;
    public static javax.swing.JTextField input;
    public static javax.swing.JLabel loc;
    public static javax.swing.JLabel ok;
    public static javax.swing.JLabel ok1;
    public static javax.swing.JLabel que;
    // End of variables declaration//GEN-END:variables
}
