/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3.player;

import java.awt.Color;

/**
 *
 * @author akash
 */
public class playlist extends javax.swing.JDialog {
    int lastX, lastY;

    /**
     * Creates new form playlist
     */
    public playlist(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playlist = new javax.swing.JLabel();
        cross = new javax.swing.JLabel();
        loc = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playlist.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playlist.setForeground(new java.awt.Color(204, 204, 204));
        playlist.setText("Playlist");
        getContentPane().add(playlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 70, 20));

        cross.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/on.png"))); // NOI18N
        cross.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cross.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                crossMouseMoved(evt);
            }
        });
        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crossMouseReleased(evt);
            }
        });
        getContentPane().add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 30));

        loc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/icon.png"))); // NOI18N
        loc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                locMouseDragged(evt);
            }
        });
        loc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                locMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                locMousePressed(evt);
            }
        });
        getContentPane().add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/playlist1.png"))); // NOI18N
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void locMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(getLocationOnScreen().x + x - lastX,getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_locMouseDragged

    private void locMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMouseClicked
        if(evt.getClickCount()==2)
        {
            this.setAlwaysOnTop(true);
        }
        if(evt.getClickCount()==3)
        {
            this.setAlwaysOnTop(false);
        }
    }//GEN-LAST:event_locMouseClicked

    private void locMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_locMousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_locMousePressed

    private void crossMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseMoved
        //cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("cross.png")));
    }//GEN-LAST:event_crossMouseMoved

    private void crossMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseReleased
        try
        {
            new Thread()
            {
                public void run()
                {
                    cross.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mp3/player/off1.png")));
                }
            }.start();
            new Thread()
            {
                public void run()
                {
                    try {
                        Thread.sleep(1000);                    
                    } catch (InterruptedException ex) {
                    }
                }
            }.start();
            this.dispose();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_crossMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                playlist dialog = new playlist(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cross;
    private javax.swing.JLabel img;
    private javax.swing.JLabel loc;
    private javax.swing.JLabel playlist;
    // End of variables declaration//GEN-END:variables

}
