/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clock;

import java.awt.Color;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author akash
 */
public class digital extends javax.swing.JDialog {
    int timerun = 0;
    int lastX, lastY;  
    byte j=1;
    wall w;
    String dn = null;

    /**
     * Creates new form digital
     */
    public digital(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
        w = new wall();
        int[] x = w.readwall();
        this.setLocation(x[0],x[1]);

        new Thread()
        {
            public void run()
        {
           while (timerun == 0) 
        {
            Calendar cal = new GregorianCalendar();
            
            int hour = cal.get(Calendar.HOUR);
            int min1 = cal.get(Calendar.MINUTE);
            int AM_PM = cal.get(Calendar.AM_PM);
            int month1 = cal.get(Calendar.MONTH);
            int day1 = cal.get(Calendar.DAY_OF_WEEK);

            time.setText(hour+"");
            if(min1==9 || min1==8 || min1==7 || min1==6 || min1==5 || min1==4 || min1==3 || min1==2 || min1==1 || min1==0)
        {
            min.setText("0"+min1+"");
        }
            else
        {
            min.setText(min1+"");
        }
            
            
            if(AM_PM == 1)
        {
            dn = "PM";
        }
            else
        {
            dn = "AM";
        }
            am.setText(dn);
          if(dn.equals("PM") && hour == 0)
            {
            time.setText("12");
            }     
            switch(month1)
            {
                case 0: month.setText("Janruary");
                    break;
                case 1: month.setText("February");
                    break;
                case 2: month.setText("March");
                    break;
                case 3: month.setText("April");
                    break;
                case 4: month.setText("May");
                    break;
                case 5: month.setText("June");
                    break;
                case 6: month.setText("July");
                    break;
                case 7: month.setText("August");
                    break;
                case 8: month.setText("September");
                    break;
                case 9: month.setText("October");
                    break;
                case 10: month.setText("November");
                    break;
                case 11: month.setText("December");
            }
            switch(day1)
            {
                case 1 : day.setText("Sunday");
                    break;
                case 2 : day.setText("Monday");
                    break;
                case 3 : day.setText("Tuesday");
                    break;
                case 4 : day.setText("Wednesday");
                    break;
                case 5 : day.setText("Thursday");
                    break;
                case 6 : day.setText("Friday");
                    break;
                 case 7 : day.setText("Saturday");
            } 
        }
        }
        }.start();
        }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drag = new javax.swing.JLabel();
        am = new javax.swing.JLabel();
        dot = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        drag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        drag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragMouseDragged(evt);
            }
        });
        drag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dragMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragMousePressed(evt);
            }
        });
        getContentPane().add(drag, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 10, 30, 20));

        am.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        am.setForeground(new java.awt.Color(153, 153, 153));
        am.setText("AM");
        am.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        am.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 20, 30));

        dot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dot.setForeground(new java.awt.Color(204, 204, 204));
        dot.setText(":");
        dot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 10, 20));

        month.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        month.setForeground(new java.awt.Color(204, 204, 204));
        month.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        month.setText(" November");
        month.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 30, -1, 20));

        day.setForeground(new java.awt.Color(255, 153, 0));
        day.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        day.setText("Saturday");
        day.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 106, 90, -1));

        time.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        time.setForeground(new java.awt.Color(102, 255, 0));
        time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time.setText("10");
        time.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 40, 30));

        min.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        min.setForeground(new java.awt.Color(102, 102, 255));
        min.setText("30");
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 30, 20));

        img.setForeground(new java.awt.Color(51, 102, 255));
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clock/digital3.png"))); // NOI18N
        img.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgMousePressed(evt);
            }
        });
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMousePressed

    }//GEN-LAST:event_imgMousePressed

    private void dragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMousePressed
lastX = evt.getXOnScreen();
lastY = evt.getYOnScreen();
    }//GEN-LAST:event_dragMousePressed

    private void dragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseDragged
try
        {
            new Thread()
            {
                public void run()
                {
                    int x = evt.getXOnScreen();
                    int y = evt.getYOnScreen();
                    setLocation(getLocationOnScreen().x + x - lastX,getLocationOnScreen().y + y - lastY);
                    lastX = x;
                    lastY = y;
                 w.writeWall((lastX)+"",(lastY)+"");
                }
            }.start();
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_dragMouseDragged

    private void dragMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragMouseClicked
if(evt.getClickCount()==3)
{
    System.exit(0);
}
    }//GEN-LAST:event_dragMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(digital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(digital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(digital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(digital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                digital dialog = new digital(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel am;
    private javax.swing.JLabel day;
    private javax.swing.JLabel dot;
    private javax.swing.JLabel drag;
    private javax.swing.JLabel img;
    private javax.swing.JLabel min;
    private javax.swing.JLabel month;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
